[cargonautica-admin]
type = s3
provider = AWS
env_auth = true
profile = cargonautica-admin
region = eu-central-1

[cargonautica-readonly]
type = s3
provider = AWS
env_auth = true
profile = cargonautica-readonly
region = eu-central-1
